# Generated by Django 5.0.1 on 2024-01-29 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0005_alter_categories_name_alter_categories_slug_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='image',
            field=models.ImageField(blank=True, default='sq.jpg', null=True, upload_to='goods_image', verbose_name='Изображение'),
        ),
    ]
