# Generated by Django 5.0.1 on 2024-02-04 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0006_alter_products_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='products',
            options={'ordering': ('id',), 'verbose_name': 'Продукт', 'verbose_name_plural': 'Продукты'},
        ),
    ]
