# Generated by Django 5.0.1 on 2024-03-02 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_status_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_on_get',
            field=models.BooleanField(default=False, verbose_name='Оплата при получении'),
        ),
    ]
