# Generated by Django 5.0.1 on 2024-03-02 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_payment_on_get'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(default='В обработке', max_length=50, verbose_name='Статус заказа'),
        ),
    ]
